In [32]:
import pandas as pd
import yaml
from IPython.display import display

error_log_path = "../.scratch/cleaned-rule-index/inventory/asca-rule-inventory-error.csv"

In [33]:
error_log = pd.read_csv(error_log_path)

error_log.head(3)

,section_index,section_name,rule_id,alt_idx,source,ok,failure_class,reason,error_token,suggested,description
0,6.1.1,Proto-Omotic to North Omotic,North-Omotic-Vː_2,NaN,index_diachronica_original.html:987,False,unknown_character,asca-unrepresentable,+,NaN,Syntax Error: Unknown character '+' | V:[+long...
1,6.1.2.1,South Omotic to Aari,"Aari-x1,x2",NaN,index_diachronica_original.html:1149,False,nested_brackets,asca-unrepresentable,NaN,NaN,Syntax Error: Cannot have nested brackets of t...
2,6.2.1.1.4,Proto-Agaw to Xamtanga,Xamtanga-k,0.0,index_diachronica_original.html:1221,False,panic_other,broken-syntax,NaN,NaN,thread panicked

In [34]:
unknown_features = error_log[error_log["failure_class"] == "unknown_feature"]
unknown_groupings = error_log[error_log["failure_class"] == "unknown_grouping"]

display(unknown_features.head(3))
display(unknown_groupings.head(3))

,section_index,section_name,rule_id,alt_idx,source,ok,failure_class,reason,error_token,suggested,description
31,7.11,Proto-Algonquian to Munsee Delaware,Munsee-Delaware-ə+weak,NaN,index_diachronica_original.html:1917,False,unknown_feature,asca-unrepresentable,weak,man,Syntax Error: Unknown feature 'weak'. Did you ...
32,7.11,Proto-Algonquian to Munsee Delaware,Munsee-Delaware-ə+weak_2,NaN,index_diachronica_original.html:1918,False,unknown_feature,asca-unrepresentable,weak,man,Syntax Error: Unknown feature 'weak'. Did you ...
33,7.11,Proto-Algonquian to Munsee Delaware,Munsee-Delaware-a+weak-ə+weak,NaN,index_diachronica_original.html:1919,False,unknown_feature,asca-unrepresentable,weak,man,Syntax Error: Unknown feature 'weak'. Did you ...

,section_index,section_name,rule_id,alt_idx,source,ok,failure_class,reason,error_token,suggested,description
83,10.2.3.1,Proto-Malayic to (Standard) Malay,Standard-Malay-V,NaN,index_diachronica_original.html:2853,False,unknown_grouping,asca-unrepresentable,U,NaN,Syntax Error: Unknown grouping 'U'. Known grou...
87,10.2.6,Proto-Malayo-Polynesian to Proto-North Sarawak,Proto-North-Sarawak-a,NaN,index_diachronica_original.html:2963,False,unknown_grouping,asca-unrepresentable,U,NaN,Syntax Error: Unknown grouping 'U'. Known grou...
88,10.2.6,Proto-Malayo-Polynesian to Proto-North Sarawak,Proto-North-Sarawak-ə_4,NaN,index_diachronica_original.html:2971,False,unknown_grouping,asca-unrepresentable,U,NaN,Syntax Error: Unknown grouping 'U'. Known grou...

In [36]:
unknown_grouping_tokens = unknown_groupings["error_token"].value_counts()
display_cols = ["section_index","rule_id", "error_token", "description"]

grouping_errors = unknown_groupings[display_cols].copy()
grouping_errors['rule'] = grouping_errors['description'].str.split(" | ", regex=False).str[1]
grouping_errors.drop(columns=['description'], inplace=True)

display(grouping_errors.head(3))

grouping_errors.to_csv("../.scratch/cleaned-rule-index/inventory/grouping_errors.csv", index=False)

   section_index                  rule_id error_token                rule
83      10.2.3.1         Standard-Malay-V           U   V > ə / _(C,0)U%#
87        10.2.6    Proto-North-Sarawak-a           U   a > ə / _%U(%,0)#
88        10.2.6  Proto-North-Sarawak-ə_4           U  ə > ∅ / #_%U(%,0)#