In [5]:
import pandas as pd

error_log_path = "../.scratch/cleaned-rule-corpus/inventory/asca-rule-inventory-error.csv"

In [6]:
error_log = pd.read_csv(error_log_path)

error_log.head()

,section_index,section_name,rule_idx,source,ok,failure_class,reason,error_token,suggested,description
0,6.1.1,Proto-Omotic to North Omotic,16,index_diachronica_original.html:987,False,unknown_character,asca-unrepresentable,+,NaN,Syntax Error: Unknown character '+' | V:[+long...
1,6.1.1.1,North Omotic to Bench,5,index_diachronica_original.html:998,False,nested_brackets,asca-unrepresentable,NaN,NaN,Syntax Error: Cannot have nested brackets of t...
2,6.1.1.5,North Omotic to Shekkacho,9,index_diachronica_original.html:1071,False,syntax_other,broken-syntax,NaN,NaN,Syntax Error: A rule cannot be both an Inserti...
3,6.1.1.5,North Omotic to Shekkacho,17,index_diachronica_original.html:1079,False,syntax_other,broken-syntax,NaN,NaN,"Syntax Error: Expected an IPA character, Prima..."
4,6.1.1.6,North Omotic to Wolaytta,3,index_diachronica_original.html:1091,False,syntax_other,broken-syntax,NaN,NaN,Syntax Error: A rule cannot be both an Inserti...

In [7]:
unknown_features = error_log[error_log["failure_class"] == "unknown_feature"]

unknown_features.head()

,section_index,section_name,rule_idx,source,ok,failure_class,reason,error_token,suggested,description
31,6.2.2.1.7,Classical Arabic to Egyptian Arabic,7,index_diachronica_original.html:1384,False,unknown_feature,asca-unrepresentable,closed,cons,Syntax Error: Unknown feature 'closed'. Did yo...
76,7.3.2,Proto-Arapaho-Atsina to Gros Ventre,1,index_diachronica_original.html:1698,False,unknown_feature,asca-unrepresentable,fallingtone,length,Syntax Error: Unknown feature 'fallingtone'. D...
98,7.11,Proto-Algonquian to Munsee Delaware,21,index_diachronica_original.html:1917,False,unknown_feature,asca-unrepresentable,weak,man,Syntax Error: Unknown feature 'weak'. Did you ...
99,7.11,Proto-Algonquian to Munsee Delaware,22,index_diachronica_original.html:1918,False,unknown_feature,asca-unrepresentable,weak,man,Syntax Error: Unknown feature 'weak'. Did you ...
100,7.11,Proto-Algonquian to Munsee Delaware,23,index_diachronica_original.html:1919,False,unknown_feature,asca-unrepresentable,weak,man,Syntax Error: Unknown feature 'weak'. Did you ...

In [11]:
tone_features = unknown_features[unknown_features["description"].str.contains("tone")]

print(tone_features.shape[0])
unique_tone_features = tone_features['error_token'].unique()

unique_tone_features

26

array(['fallingtone', 'hightone', 'lowtone', 'lowfallingtone',
       'highrisingtone'], dtype=object)