In [1]:
import pandas as pd

error_log_path = "../.scratch/cleaned-rule-index/inventory/asca-rule-inventory-error.csv"

In [2]:
error_log = pd.read_csv(error_log_path)

error_log.head()

,section_index,section_name,rule_id,alt_idx,source,ok,failure_class,reason,error_token,suggested,description
0,6.1.1,Proto-Omotic to North Omotic,North-Omotic-Vː_2,NaN,index_diachronica_original.html:987,False,unknown_character,asca-unrepresentable,+,NaN,Syntax Error: Unknown character '+' | V:[+long...
1,6.1.1.7,North Omotic to Yemsa,Yemsa-kʼ,NaN,index_diachronica_original.html:1110,False,expected_underscore,asca-unrepresentable,NaN,NaN,"Syntax Error: Expected '_', but received '' | ..."
2,6.1.2.1,South Omotic to Aari,"Aari-x1,x2",NaN,index_diachronica_original.html:1149,False,unknown_character,asca-unrepresentable,₁,NaN,"Syntax Error: Unknown character '₁' | {x₁,x₂} ..."
3,6.2.1.1.4,Proto-Agaw to Xamtanga,Xamtanga-k,0.0,index_diachronica_original.html:1221,False,panic_other,broken-syntax,NaN,NaN,thread panicked
4,6.2.2.1.1,Proto-North Erythrean to Proto-Boreafrasian,Proto-Boreafrasian-z,NaN,index_diachronica_original.html:1248,False,expected_underscore,asca-unrepresentable,NaN,NaN,"Syntax Error: Expected '_', but received '' | ..."

In [3]:
unknown_features = error_log[error_log["failure_class"] == "unknown_feature"]

unknown_features.head()

,section_index,section_name,rule_id,alt_idx,source,ok,failure_class,reason,error_token,suggested,description
21,6.2.2.1.7,Classical Arabic to Egyptian Arabic,Egyptian-Arabic-aj-aw,NaN,index_diachronica_original.html:1384,False,unknown_feature,asca-unrepresentable,closed,cons,Syntax Error: Unknown feature 'closed'. Did yo...
84,7.11,Proto-Algonquian to Munsee Delaware,Munsee-Delaware-ə+weak,NaN,index_diachronica_original.html:1917,False,unknown_feature,asca-unrepresentable,weak,man,Syntax Error: Unknown feature 'weak'. Did you ...
85,7.11,Proto-Algonquian to Munsee Delaware,Munsee-Delaware-ə+weak_2,NaN,index_diachronica_original.html:1918,False,unknown_feature,asca-unrepresentable,weak,man,Syntax Error: Unknown feature 'weak'. Did you ...
86,7.11,Proto-Algonquian to Munsee Delaware,Munsee-Delaware-a+weak-ə+weak,NaN,index_diachronica_original.html:1919,False,unknown_feature,asca-unrepresentable,weak,man,Syntax Error: Unknown feature 'weak'. Did you ...
101,8.3,Proto-Altaic to Proto-Mongolic,Proto-Mongolic-pʰ_3,NaN,index_diachronica_original.html:2186,False,unknown_feature,asca-unrepresentable,highpitch,high,Syntax Error: Unknown feature 'highpitch'. Did...

In [4]:
tone_features = unknown_features[unknown_features["description"].str.contains("tone")]

print(tone_features.shape[0])
unique_tone_features = tone_features['error_token'].unique()

unique_tone_features

2

array(['fallingtone'], dtype=object)