In [8]:
import pandas as pd
import yaml
from IPython.display import display

error_log_path = "../.scratch/cleaned-rule-index/inventory/asca-rule-inventory-error.csv"

In [9]:
error_log = pd.read_csv(error_log_path)

error_log.head(3)

,section_index,section_name,rule_id,alt_idx,source,ok,failure_class,reason,error_token,suggested,description
0,6.1.1,Proto-Omotic to North Omotic,North-Omotic-Vː_2,NaN,index_diachronica_original.html:987,False,unknown_character,asca-unrepresentable,+,NaN,Syntax Error: Unknown character '+' | V:[+long...
1,6.1.2.1,South Omotic to Aari,"Aari-x1,x2",NaN,index_diachronica_original.html:1149,False,nested_brackets,asca-unrepresentable,NaN,NaN,Syntax Error: Cannot have nested brackets of t...
2,6.2.1.1.4,Proto-Agaw to Xamtanga,Xamtanga-k,0.0,index_diachronica_original.html:1221,False,panic_other,broken-syntax,NaN,NaN,thread panicked

In [10]:
unknown_features = error_log[error_log["failure_class"] == "unknown_feature"]
unknown_groupings = error_log[error_log["failure_class"] == "unknown_grouping"]
unknown_characters = error_log[error_log["failure_class"] == "unknown_character"]
expected_underscores = error_log[error_log["failure_class"] == "expected_underscore"]

display(unknown_features.head(3))
display(unknown_groupings.head(3))
display(unknown_characters.head(3))
display(expected_underscores.head(3))

,section_index,section_name,rule_id,alt_idx,source,ok,failure_class,reason,error_token,suggested,description
25,7.11,Proto-Algonquian to Munsee Delaware,Munsee-Delaware-ə+weak,NaN,index_diachronica_original.html:1917,False,unknown_feature,asca-unrepresentable,weak,man,Syntax Error: Unknown feature 'weak'. Did you ...
26,7.11,Proto-Algonquian to Munsee Delaware,Munsee-Delaware-ə+weak_2,NaN,index_diachronica_original.html:1918,False,unknown_feature,asca-unrepresentable,weak,man,Syntax Error: Unknown feature 'weak'. Did you ...
27,7.11,Proto-Algonquian to Munsee Delaware,Munsee-Delaware-a+weak-ə+weak,NaN,index_diachronica_original.html:1919,False,unknown_feature,asca-unrepresentable,weak,man,Syntax Error: Unknown feature 'weak'. Did you ...

,section_index,section_name,rule_id,alt_idx,source,ok,failure_class,reason,error_token,suggested,description
128,14.3.1,Standard Tamil to Colloquial Tamil,Colloquial-Tamil-∅_2,NaN,index_diachronica_original.html:4549,False,unknown_grouping,asca-unrepresentable,M,NaN,Syntax Error: Unknown grouping 'M'. Known grou...
172,17.5.1,Proto-Indo-European to Old Irish,Old-Irish-p-t-k-kʷ-b-d-ɡ-m-n-l-r-s,NaN,index_diachronica_original.html:5521,False,unknown_grouping,asca-unrepresentable,M,NaN,Syntax Error: Unknown grouping 'M'. Known grou...
227,17.7.2.3,Middle High German to Standard German,Standard-German-∅,NaN,index_diachronica_original.html:6121,False,unknown_grouping,asca-unrepresentable,M,NaN,Syntax Error: Unknown grouping 'M'. Known grou...

,section_index,section_name,rule_id,alt_idx,source,ok,failure_class,reason,error_token,suggested,description
0,6.1.1,Proto-Omotic to North Omotic,North-Omotic-Vː_2,NaN,index_diachronica_original.html:987,False,unknown_character,asca-unrepresentable,+,NaN,Syntax Error: Unknown character '+' | V:[+long...
6,6.2.2.1.8,Classical Arabic to Coastal Hadhrami Arabic,Coastal-Hadhrami-Arabic-aː,NaN,index_diachronica_original.html:1409,False,unknown_character,asca-unrepresentable,‘,NaN,Syntax Error: Unknown character '‘' | a:[+long...
7,6.2.2.1.9,Classical Arabic to Wādı̄ Hadhrami Arabic,Wādı̄-Hadhrami-Arabic-aː,NaN,index_diachronica_original.html:1420,False,unknown_character,asca-unrepresentable,‘,NaN,Syntax Error: Unknown character '‘' | a:[+long...

,section_index,section_name,rule_id,alt_idx,source,ok,failure_class,reason,error_token,suggested,description
8,6.2.2.1.17,Classical Arabic to Tunisian Arabic,Tunisian-Arabic-Vː_2,NaN,index_diachronica_original.html:1507,False,expected_underscore,asca-unrepresentable,NaN,NaN,"Syntax Error: Expected '_', but received '' | ..."
10,6.2.2.1.18,Proto-Semitic to Biblical Hebrew,Biblical-Hebrew-p-b-t-d-k-ɡ,NaN,index_diachronica_original.html:1546,False,expected_underscore,asca-unrepresentable,NaN,NaN,"Syntax Error: Expected '_', but received '' | ..."
11,6.2.2.1.19,Biblical Hebrew to Modern Israeli Hebrew,Modern-Israeli-Hebrew-ʔ,NaN,index_diachronica_original.html:1564,False,expected_underscore,asca-unrepresentable,NaN,NaN,"Syntax Error: Expected '_', but received '' | ..."

In [11]:
display_cols = ["section_index","rule_id", "error_token", "description"]

grouping_errors = unknown_groupings[display_cols].copy()
grouping_errors['rule'] = grouping_errors['description'].str.split(" | ", regex=False).str[1]
grouping_errors.drop(columns=['description'], inplace=True)

display(grouping_errors.head(3))

grouping_errors.to_csv("../.scratch/cleaned-rule-index/inventory/grouping_errors.csv", index=False)

,section_index,rule_id,error_token,rule
128,14.3.1,Colloquial-Tamil-∅_2,M,"∅ > ʉ / {l,ɭ}_# if {M,V:[+long]} previously in..."
172,17.5.1,Old-Irish-p-t-k-kʷ-b-d-ɡ-m-n-l-r-s,M,p t k kʷ b d ɡ m n l r s > f θ x xʷ v ð ɣ M N ...
227,17.7.2.3,Standard-German-∅,M,∅ > ə / M_r$

In [12]:
display_cols = ["section_index","rule_id", "error_token", "description"]

character_errors = unknown_characters[display_cols].copy()
character_errors['rule'] = character_errors['description'].str.split(" | ", regex=False).str[1]
character_errors.drop(columns=['description'], inplace=True)

display(character_errors.head(3))

character_errors.to_csv("../.scratch/cleaned-rule-index/inventory/character_errors.csv", index=False)

,section_index,rule_id,error_token,rule
0,6.1.1,North-Omotic-Vː_2,+,V:[+long] > V / #C_C$ + $(V)C$ suffix
6,6.2.2.1.8,Coastal-Hadhrami-Arabic-aː,‘,a:[+long] > e:[+long] / Form VI (tafa:[+long]‘...
7,6.2.2.1.9,Wādı̄-Hadhrami-Arabic-aː,‘,a:[+long] > e:[+long] / Form VI (tafa:[+long]‘...

In [15]:
underscore_errors = expected_underscores[display_cols].copy()
underscore_errors['rule'] = underscore_errors['description'].str.split(" | ", regex=False).str[1]
underscore_errors.drop(columns=['description'], inplace=True)

display(underscore_errors.head(30))

,section_index,rule_id,error_token,rule
8,6.2.2.1.17,Tunisian-Arabic-Vː_2,NaN,V:[+long] > V:[+long] / accented or stressed m...
10,6.2.2.1.18,Biblical-Hebrew-p-b-t-d-k-ɡ,NaN,p b t d k ɡ > b v θ ð x ɣ / non-intial singletons
11,6.2.2.1.19,Modern-Israeli-Hebrew-ʔ,NaN,ʔ > ∅ // onset of %[+stress]
16,7.3.2,Gros-Ventre-j,NaN,"j > ∅ / :{ʃ,θ}:"
19,7.4,Blackfoot-aː_2,NaN,a:[+long] > a / else
20,7.9,Swampy-Cree-ʃ,NaN,ʃ > s / Gest Pwampy Cree
21,7.11,Munsee-Delaware-tʃ,NaN,tʃ > t / nouns
24,7.11,Munsee-Delaware-V,NaN,V > ∅ / _# // some monosyllables and analogica...
28,7.12,Menominee-æ,NaN,"æ > e / odd syllables // _{w,j,[-place]}"
29,7.13,Miami-Illinois-VNs-VNʃ,NaN,VNs VNʃ > V[+nas]z V[+nas]ʒ / not universal?
33,8.1,Proto-Japonic-tʃ,NaN,tʃ > s / maybe // _#?
36,8.3,Proto-Mongolic-b,NaN,"b > h / medially, // {r,rʲ,l,lʲ}_ or _ɡ"
40,8.5.1,Proto-Kypchak-ŋ,NaN,ŋ > ɡ / syllable-final
46,10.1.2.4,Ibanag-*j,NaN,j > ɡ / possible exception in word-initial pos...
50,10.2.4.1,Javanese-b,NaN,b > w // adjacent to another consonant
52,10.2.5,Palauan-t,NaN,t > ð // adjacent to P
54,10.2.6.1,Kiput-əi̯-əu̯,NaN,əi̯ əu̯ > ai̯ au̯ // O[+voice] earlier in the ...
57,10.3.2,Hiw-β-b-m,NaN,β b m > βʷ bʷ mʷ / typically near *u
70,10.3.5.3,Nemi-Pije-Fwai-ONV,NaN,ONV > C:[+labial][+spread]ṽ / C:[+labial]ije ...
71,10.3.5.3,Nemi-Pije-Fwai-f,NaN,f > ɸ / C:[+labial]ije and Fwai
72,10.3.5.4.1,Nixumwak-Nêlêmwa-V,NaN,"V > ∅ / _#, often"
85,10.3.5.8,Proto-Yunaga-u-i,NaN,u i > o e / monosyllables
90,10.3.10.3,Vano-t,NaN,"t > l / #_, in nouns"
129,14.3.1,Colloquial-Tamil-i-u_2,NaN,i u > ɨ ʉ / _ when unstressed // #%
130,14.3.1,Colloquial-Tamil-∅_3,NaN,∅ > ɨ / to break up clusters
131,14.3.1,Colloquial-Tamil-∅_3,NaN,∅ > ʉ / to break up clusters
144,15.2.7,Siberian-Yup’ik-C+voice,NaN,"C[+voice] > C[-voice] / next to {P,s,l̥}"
145,15.2.7,Siberian-Yup’ik-ə,NaN,ə > a /
148,15.2.8,Unaaliq-Yup’ik-C+voice,NaN,"C[+voice] > C[-voice] / next to {P,s,l̥}"
152,17.2,Common-Anatolian-T-h2_3,NaN,"P:[-voice] x > P:[+voice] ɣʷ / V:[+stress, +long]"