In [5]:
import os
import sys
import subprocess
import pandas as pd
from IPython.display import display

RULES_DIR = "./data/rules"

In [6]:
sections_df = pd.read_csv("./data/index_diachronica_sections.csv", dtype={"index": str, "name": str, "rule_count": int})

rules_df = sections_df[sections_df["rule_count"] > 0].copy()
rules_df['asca_rule_file'] = rules_df['index'].apply(lambda x: f"{x}.rsca")
rules_df['brassica_rule_file'] = rules_df['index'].apply(lambda x: f"{x}.bsc")

display(rules_df.head(3))

asca_rule_files = rules_df['asca_rule_file'].tolist()
brassica_rule_files = rules_df['brassica_rule_file'].tolist()

,index,name,rule_count,asca_rule_file,brassica_rule_file
1,6.1,Proto-Afro-Asiatic to Proto-Omotic,11,6.1.rsca,6.1.bsc
2,6.1.1,Proto-Omotic to North Omotic,18,6.1.1.rsca,6.1.1.bsc
3,6.1.1.1,North Omotic to Bench,9,6.1.1.1.rsca,6.1.1.1.bsc

In [7]:
# run asca-rust to validate rules

asca_results = []
asca_word_file = "./data/words/asca/weirdness_0.5.wsca"

def run_asca(asca_word_file, rule_file):
    cmd = f"~/.cargo/bin/asca run {asca_word_file} -r {RULES_DIR}/asca/{rule_file}"

    result = {"rule": rule_file, "returncode": 0, "error": ""}

    try:
        output = subprocess.run(cmd, capture_output=True, timeout=10, shell=True, text=True)
        output.check_returncode()

    except subprocess.CalledProcessError as exc:
        result["returncode"] = exc.returncode 
        result["error"] = exc.output.replace("\n", "\\n")
    except subprocess.TimeoutExpired as exc:
        result["returncode"] = 124
        result["error"] = exc.output.decode("utf-8").replace("\n", "\\n")

    return result

for rule_file in asca_rule_files[:10]:
    result = run_asca(asca_word_file, rule_file)
    asca_results.append(result)

asca_results_df = pd.DataFrame(asca_results)

asca_results_df.to_csv("./data/asca_results.csv", index=False)

asca_results_df[asca_results_df["returncode"] != 0].head()

Empty DataFrame
Columns: [rule, returncode, error]
Index: []

In [ ]:
# run Brassica to validate rules

brassica_results = []
brassica_word_file = "./data/words/brassica/weirdness_0.5.lex"

def run_brassica(brassica_word_file, rule_file):
    cmd = f"brassica {RULES_DIR}/brassica/{rule_file} -i {brassica_word_file}"

    result = {"rule": rule_file, "returncode": 0, "error": ""}

    try:
        print(cmd)
        output = subprocess.run(cmd, capture_output=True, timeout=10, shell=True, text=True)
        print(output.stdout)
        output.check_returncode()

    except subprocess.CalledProcessError as exc:
        result["returncode"] = exc.returncode 
        result["error"] = exc.output.replace("\n", "\\n")
    except subprocess.TimeoutExpired as exc:
        result["returncode"] = 124
        result["error"] = exc.output.decode("utf-8").replace("\n", "\\n")

    return result

for rule_file in brassica_rule_files[:10]:
    result = run_brassica(brassica_word_file, rule_file)
    brassica_results.append(result)

brassica_results_df = pd.DataFrame(brassica_results)

brassica_results_df.to_csv("./data/brassica_results.csv", index=False)

brassica_results_df[brassica_results_df["returncode"] != 0].head()

brassica ./data/rules/brassica/6.1.bsc -i ./data/words/brassica/weirdness_0.5.lex
CompletedProcess(args='brassica ./data/rules/brassica/6.1.bsc -i ./data/words/brassica/weirdness_0.5.lex', returncode=0, stdout='4:12:\n  |\n4 | dʒ / tʃ / ʃ\n  |            ^\nunexpected newline\nexpecting "%(", \'#\', \'$\', \'%\', \'(\', \'*\', \'>\', \'@\', \'[\', \'^\', \'_\', or \'~\'\n\n', stderr='')
brassica ./data/rules/brassica/6.1.1.bsc -i ./data/words/brassica/weirdness_0.5.lex
CompletedProcess(args='brassica ./data/rules/brassica/6.1.1.bsc -i ./data/words/brassica/weirdness_0.5.lex', returncode=0, stdout='5:12:\n  |\n5 | e / i / #l_{P,C[+voiced]}\n  |            ^\nunexpected \'{\'\nexpecting "%(", "-1", "->", "-?", "-??", "-ltr", "-no", "-rtl", "-x", "//", "categories", "extra", "filter", "new", "report", \'#\', \'%\', \'(\', \'*\', \'/\', \'>\', \'@\', \'[\', \'^\', \'→\', or end of input\n\n', stderr='')
brassica ./data/rules/brassica/6.1.1.1.bsc -i ./data/words/brassica/weirdness_0.5.lex
CompletedProcess(args='brassica ./data/rules/brassica/6.1.1.1.bsc -i ./data/words/brassica/weirdness_0.5.lex', returncode=0, stdout='8:1:\n  |\n8 | {ʔ,hx} / ∅\n  | ^\nunexpected \'{\'\nexpecting "%(", "-1", "->", "-?", "-??", "-ltr", "-no", "-rtl", "-x", "categories", "extra", "filter", "new", "report", \'#\', \'%\', \'(\', \'*\', \'/\', \'>\', \'@\', \'[\', \'^\', \'→\', or end of input\n\n', stderr='')
brassica ./data/rules/brassica/6.1.1.2.bsc -i ./data/words/brassica/weirdness_0.5.lex
CompletedProcess(args='brassica ./data/rules/brassica/6.1.1.2.bsc -i ./data/words/brassica/weirdness_0.5.lex', returncode=0, stdout='9:5:\n  |\n9 | ʒ / {tʃ,ts}\n  |     ^\nunexpected \'{\'\nexpecting "%(", "-1", "->", "-?", "-??", "-ltr", "-no", "-rtl", "-x", "//", "@?", "categories", "extra", "filter", "new", "report", \'#\', \'%\', \'(\', \'*\', \'/\', \'>\', \'@\', \'[\', \'\\\', \'^\', \'~\', \'→\', or end of input\n\n', stderr='')
brassica ./data/rules/brassica/6.1.1.3.bsc -i ./data/words/brassica/weirdness_0.5.lex
CompletedProcess(args='brassica ./data/rules/brassica/6.1.1.3.bsc -i ./data/words/brassica/weirdness_0.5.lex', returncode=0, stdout='3:10:\n  |\n3 | b / w / _$#\n  |          ^\nunexpected \'$\'\nexpecting "%(", "-1", "->", "-?", "-??", "-ltr", "-no", "-rtl", "-x", "//", "categories", "extra", "filter", "new", "report", \'#\', \'%\', \'(\', \'*\', \'/\', \'>\', \'@\', \'[\', \'^\', \'→\', or end of input\n\n', stderr='')
brassica ./data/rules/brassica/6.1.1.4.bsc -i ./data/words/brassica/weirdness_0.5.lex
CompletedProcess(args='brassica ./data/rules/brassica/6.1.1.4.bsc -i ./data/words/brassica/weirdness_0.5.lex', returncode=0, stdout="non [be]\nnwe [become]\nbjenja [cause]\nwipwəman [make]\na [do]\njiŋitwi [have]\njedaŋ [is/are able to...]\nbəŋɾoŋ [this]\nfwənɛmwam [that]\nŋjɛ [here (in/to this place)]\nowiaŋ [how?]\nɾjuman [not]\nuja [only]\nloem [there (at/to that place)]\nswomoŋ [together]\njajo [when?]\nwowowuŋ [where?]\njwɛn [why?]\nu [any]\nŋwetaŋa [every]\njohjawa [person]\njoŋ [baby]\nzjun [boy]\nɡim [girl]\nuŋwoŋwɛ [man]\njəŋ [woman]\njowo [family]\nmjoŋ [father]\nenjjeiŋ [mother]\nnaam [son]\noɛ [daughter]\nromjomhja [brother]\nwjɛŋowɛ [sister]\njowɛŋhwom [chief]\nobənɛ [friend]\nwu [society]\nkoiŋo [committee]\nijɛŋaŋ [nation]\no [public]\nlwijouŋ [arm]\nlemjaŋwjə [back]\njɛɛn [blood]\njenwe [body]\nəŋjozjə [bone]\nmwunjən [brain]\nwan [chest]\ndwa [chin]\nkɛ [ear]\njweŋpjuŋdwaŋ [egg]\nkwo [eye]\nljəswɛn [face]\nhwitsɛ [feather]\nwu [finger]\nɡɛ [foot]\njo [hair]\ntsojajjeŋ [hair]\nije [hand]\nnamrjen [head]\no [heart]\ni [horn (bone-like growth from animal's head)]\nmeʃwowu [knee]\nswi [leg]\njimjɛŋə [lip]\nu [meat]\nhjem [mouth]\nzjaŋ [muscle]\nənpu [nail / finger nail]\nwo [neck]\nwənzwaŋ [nerve]\nhwoŋewa [nose]\nənwi [skin]\nbe [stomach]\nwun [tail]\nɛ [throat]\nrjeka [thumb]\namlwan [toe]\nʃon [tongue (body-part)]\nfɛuən [tooth]\nnje [blood vessel]\njurən [wing (of bird)]\nəŋjɛwi [wound]\njənwaən [berry (small fruit)]\nwəmjin [flower]\nɾu [fruit]\nənowa [leaf]\nokjin [nut]\nʃən [root (of a plant)]\ntjuŋwoŋ [seed]\nwepjɛnjum [dead]\nuŋ [birth]\naŋtsɛhji [healthy]\nkji [disease]\nrwəm [fat]\nɛwanɡji [sex]\namwɛ [female]\nʃwum [male]\njənjora [sense]\njoŋjuŋ [pain]\nəm [pleasure]\nɛwumkjuŋ [tired]\ntsəjɛndom [sleep]\njoopwon [awake]\nwodjɛŋɾɛŋ [bite]\nʃwoŋ [have sex (with)]\nŋo [cry out]\njiwam [cry]\nŋjo [drink]\nfa [jump]\nosomzjuŋ [kick]\noŋ [kiss]\nwoŋ [laugh]\ndɛn [run]\nem [smile]\nwuŋpim [sneeze]\nwekamɡaŋ [swim]\nɡwəŋrwu [taste]\nou [touch]\nosemwɛm [walk]\nkwanhəŋan [animal]\nɡɛ [ant]\njjeŋwu [bee]\njumɾjɛwun [bird]\nfiəe [cat]\nluŋrom [cow]\njefwəŋhom [dog]\ntwimɡaŋŋwoŋ [fish]\nwom [fly]\nkjom [goat]\nwunɛŋ [horse]\nonwoŋ [insect]\ndɛ [monkey]\ndahəŋ [pig]\nziwenju [sheep]\nwenjin [snake]\npənkjeŋjɛ [worm]\njəbəmja [apple]\nzwejɛəŋ [cork]\nɛŋwojim [cotton]\nwəŋ [grass]\ntu [orange]\nmiŋ [potato]\nherjɛŋ [rice]\nɛŋdwɛ [garden]\nmwojjə [grain]\nʃwenomo [plant]\nraŋ [tree]\nwə [cloud]\nrjɛŋ [earth]\nɡuhjaŋ [field]\nbwuŋ [island]\nja [moon]\nomanjən [mountain]\nejoŋ [rain]\niŋjwɛŋtwə [river]\nwə [sky]\nnenjawəm [snow]\nenɾɛnlji [star]\njam [sun]\nroŋ [thunder]\nwiɛnoŋ [weather]\nəntsji [wind]\nilwunte [rod]\nnjəkwuo [basket]\nwamhɛmjɛm [bed]\nrwə [bell]\naŋkanun [blade]\nrumjen [board]\nhwiŋzonɛŋ [bottle]\njoowaŋ [box]\nta [brake]\njiŋkunwə [brick]\nrəm [brush]\nŋaŋji [button]\nɡjajini [chain]\nljamun [clock]\nʃwoŋoi [comb]\nwen [cord]\nnwu [cover]\nmweŋdjɛ [cup]\ndwɛrwɛm [curtain]\njan [drain]\nwum [fork]\njən [frame]\njɛ [gun]\njaŋjɛɛŋ [hammer]\nuŋnwijem [hook]\nrəaŋ [horn]\nomaŋnju [key]\nuŋi [knife]\nwon [lock]\nmjaweŋ [machine]\nɾe [match (little fire-stick)]\ntsjə [engine]\nəmhwɛŋ [nail]\njosji [needle]\nmenɛ [net]\nɾi [oven]\nŋju [parcel]\nezə [pen]\nwuŋon [pencil]\nhi [cushion]\nwonɛm [pipe]\njə [plate]\nja [plough]\nweanlweŋ [pocket]\nɛmwaŋhəm [stick]\nlen [pot (deep round vessel)]\njumkjəmpo [pump]\njenwo [rail]\njojwojin [bag]\nwəm [sail]\njəmjoʃwum [scale]\nʃɛen [scissors]\njeŋi [screw]\nʃwə [sign]\nojo [shelf]\nɡjanɛnɡwum [sponge]\nzwa [spoon]\njoŋwuswə [spring]\nifa [table]\njiŋə [tray]\npjaməa [umbrella]\njoki [wheel]\nwumnwomfwen [wire]\nuŋenə [coat]\nwəmlandən [collar]\nwi [glove]\najə [trousers]\njuɡjəse [shirt]\nnwɛamɾju [shoe]\nnwu [skirt / dress]\nwjen [building]\nbaɛwjəm [door]\njinɡəa [lift]\nwizəmdə [floor]\ndo [roof]\nsuhjama [wall]\ndamʃjiŋjon [window]\nwaɛn [church]\nwam [hospital]\nkɛ [house]\niŋ [library]\ne [school]\npɛnjankə [bridge]\nwa [farm]\njɛŋ [market]\naŋ [army]\nwe [authority]\nnwɛwɛrwuŋ [control]\nuinəŋ [crime]\nin [free]\nənjaɡəm [government]\neən [law]\noorɛ [military]\nmupɛŋswo [nation]\nujɛtswun [let]\naŋjuwɛ [tax]\nrwun [war]\nelwudjin [account]\nroŋwo [company (a business organization)]\ntswiə [credit]\nun [give]\npe [insurance]\nɡwe [keep]\noɡjinsu [money]\nzjinjəjə [offer]\ndjemɾjimɛn [private]\nwəm [public]\nda [reward]\naŋhjɛŋ [take]\njə [value]\nja [religion]\nzwɛwu [angry]\nswɛtsamdjo [art]\nwə [attention]\nwu [care]\njamʃjeə [comfort]\npəjijjəŋ [doubt]\nʃwijin [experience]\nwə [fear]\npəŋɡɛnja [foolish]\noŋfjoa [guide / lead]\ndjumou [happy]\nim [hate]\nwɛ [hope]\naŋzunboŋ [important]\njəiŋ [interest]\nʃuŋ [judge]\nmjemjənmə [knowledge]\npwətswu [love]\nɡe [mind]\nwəimjaŋ [kind]\ntazəmjem [opinion]\nwɛnhje [peace]\nwan [design]\nŋɛaŋ [play]\nəio [act]\naɛmje [self-respect]\nəŋjeti [thought]\njəŋwewwo [regret]\nbəŋaŋ [look for]\nehjɛ [shame]\nwohwum [theory]\nə [desire]\nwo [wise]\npiwɛɛ [advertisement]\nmja [book]\nkwa [order]\nfəo [talk about]\nwamwain [fact]\nɡweŋwaməŋ [fiction]\nje [history]\njiŋswɛ [be a sign of]\njo [language]\njəkwawɛ [letter]\nunəm [list]\njəm [map]\ni [motion picture]\nujɛom [name]\njɛ [noise]\nim [page]\npjo [print]\njəŋɛnɡjaŋ [record]\ntwɛm [secret]\ndjaaŋwo [sign]\nŋafən [voice]\nzaŋ [word]\nuwa [match]\njejoŋi [ball]\nʃonwi [stick]\niwumli [different]\njowe [change]\nonjo [copy]\nən [amount / number]\nswaŋkozum [number]\nɛ [measure]\njeiŋ [rate]\nɛʃwamje [rest (of...)]\njwɛŋjum [complete]\nawizjə [all]\nwa [a small number of]\nɛŋoŋ [group]\npjaon [degree]\neaŋtswe [much / very]\njujɛ [little]\nhweŋŋeŋ [size]\nawaim [distance]\nləsjiŋ [far]\naŋjjunjo [near]\ntswam [present]\no [wide]\nfɛ [narrow]\nɡiŋ [thick / fat]\nʃjojum [thin]\njjemjwɛsa [low / short]\nwiŋ [angle]\njunŋjamtswum [position]\npamjo [front]\nin [back part of]\nzerwizɛ [edge]\nnjɛŋtwamfe [direction]\njaŋem [up]\nnwaoə [down]\nwa [north]\nwə [south]\nɾjeŋ [east]\nweon [west]\nwuwoəŋ [right(-hand)]\npi [left(-hand)]\njuwo [back]\nwwuwəwoŋ [base / station]\nmwumwa [come]\nɾwemowa [go into]\nwaŋjuŋ [fly (move through the air)]\nɡjojanŋjom [go]\naʃjəja [come across]\nbonoŋ [roll]\npuŋwuri [slip]\no [boat]\nwuhinlwuŋ [cart / carriage]\nrjɛmo [road]\nta [ship]\nkɛnzone [street]\nmwə [train]\nətsja [young]\nwejun [old]\nwajɛpjeŋ [new]\nʃjime [old]\nɡjirjun [rhythm]\nlɛwjumbe [time]\nŋenon [start]\nɡwe [stop]\nrei [ever (at any time)]\nwweŋjɛ [time]\nɛn [past]\nɛnomu [the present]\njumtɛŋtsju [future]\nljumɛn [still]\nu [yesterday]\nwəŋ [tomorrow]\nfjinwaŋa [in the near past]\njomisi [now / at this time]\nlojja [in the near future]\nswuŋ [in the far future]\nbjɛ [on time]\nbon [order]\ndamoŋjen [spring]\nfanbjədjen [summer]\nhwɛ [fall]\nwam [winter]\ndwiŋwaɛŋ [year]\neŋ [month]\njamu [week]\njwum [day]\nhiwwomhuŋ [day]\nwinwin [night]\nɛŋ [morning]\nɡa [middle of the night]\nwə [hour]\nɡwomin [minute]\nwabun [second]\nhi [air]\njiɡwəʃjɛm [brass]\nwuŋfwenuŋ [chalk]\njiŋtjəŋ [chemical]\ntɛŋjə [cloth]\nuŋotsan [coal]\nhjiu [copper]\njeɛn [earth]\nŋwə [dust]\nwjaiŋu [glass]\nromsa [gold]\nzɛ [ice]\nsɛm [ink]\ntswɛmimɛ [iron]\nhweɾwum [lead (the metal)]\nwe [leather]\nwən [metal]\niowi [oil]\nwem [paint]\nənwomwe [paper]\nju [stone]\nwweŋ [salt]\nsjɛbən [sand]\nkjɛmjonbwɛm [silk]\njaŋiŋ [silver (the metal)]\nwodjemwaŋ [soap]\ntjamja [steam]\nu [steel]\nkjeŋoŋ [tin (the metal)]\njimjwəŋji [water]\nawwaŋ [wax]\nie [wood (the substance)]\nzwarjom [wool]\nwɛŋ [bitter]\nlwem [bread]\njəen [butter]\nɛm [cheese]\nɾjɛn [taste]\njɛŋ [grain-powder]\nkweŋlwodim [food]\nutem [milk]\nŋwɛmhunjo [soup]\nimimwə [sugar]\njumem [sweet]\nmjəan [wine]\ntswəm [arch]\nwo [branch]\nbiŋe [card]\nku [circle]\ntsunswəŋ [curve]\nu [drop (of liquid)]\nswin [hole]\nzwem [jelly]\nnwi [line]\ndwɛ [liquid]\nwɛn [mark]\ntjo [material / substance]\nho [parallel]\njiu [paste]\nʃjun [powder]\ntsjəŋəmtɛŋ [ray]\nwɛ [smoke]\nwimsimrwum [solid]\nloŋ [square]\no [wave]\njumtoiŋ [level / even (on the same level)]\nɡje [smooth]\noŋ [straight / not bent]\nwaŋə [bent]\nujje [clean]\njo [open / not shut]\nɛn [shut]\nwəŋ [wet]\nʃəmfi [dry]\nnjunjoŋ [elastic]\ntwɛ [strong]\nbjujam [delicate]\nrwo [weight]\ndwoje [of much weight]\njaŋemtjin [light / of little weight]\nam [solid]\nieŋaŋ [hollow]\nɛnnjilwɛ [loose]\npəom [tight]\nenju [thick]\nəmjwaŋljən [blow]\ntsɛtswamdwa [burn]\nkwi [burst]\npaən [crush]\njəkjowiŋ [fold]\nljunjwəŋ [pull]\njjudjewu [push]\nkjəŋjae [shake]\nko [wash]\nsjəm [acid]\nŋjunuŋa [fire]\nwinjɛu [force]\nu [power]\nnju [a blow of force]\nɡuŋa [mist]\njula [see]\nrwaim [light]\nmjejeŋ [colour]\nnimboŋɡə [shade]\nŋaemsaŋ [bright]\njuŋwe [dark]\nəŋwobjum [black]\nna [grey]\nwatɛu [white]\nwen [red]\nɾeŋəŋ [orange]\nan [yellow]\nljo [green]\nmje [blue]\nwɛbwane [brown]\nmə [beautiful]\njaŋe [sound]\nimjiwan [quiet / soft]\nə [loud]\nɛ [hear]\njəm [music]\nwo [whistle]\ndwum [of little heat]\nʃwasunwɛŋ [warm]\nuŋ [of very much heat]\nwonə [cook]\nannwam [cook]\nlamzaə [attack]\nwum [good]\npəəntjun [bad]\nʃjuwum [kind / sort]\nmjulwəmɛ [probable]\nzwewe [simple]\nsem [complex]\nɡɛɛŋni [make]\nu [danger]\nnje [hard]\njomjoŋ [true]\niŋum [damage]\nan [special]\nwumwo [automatic]\npwɛ [detail]\npitwujɛm [equal]\no [fertile]\nəŋ [harmony]\nfjɛ [match]\nin [right (a right to do/be...)]\njoŋ [system]\nwamjə [attempt]\nowɛ [science]\nlənweŋ [support]\n", stderr='')
brassica ./data/rules/brassica/6.1.1.5.bsc -i ./data/words/brassica/weirdness_0.5.lex
CompletedProcess(args='brassica ./data/rules/brassica/6.1.1.5.bsc -i ./data/words/brassica/weirdness_0.5.lex', returncode=0, stdout='6:9:\n  |\n6 | z / j / {#,V}_\n  |         ^\nunexpected \'{\'\nexpecting "%(", \'#\', \'%\', \'(\', \'*\', \'>\', \'@\', \'[\', \'^\', or \'_\'\n\n', stderr='')
brassica ./data/rules/brassica/6.1.1.6.bsc -i ./data/words/brassica/weirdness_0.5.lex
CompletedProcess(args='brassica ./data/rules/brassica/6.1.1.6.bsc -i ./data/words/brassica/weirdness_0.5.lex', returncode=0, stdout='7:17:\n  |\n7 | x₂ s₃ / k ʃ / V_$#\n  |                 ^\nunexpected \'$\'\nexpecting "%(", "-1", "->", "-?", "-??", "-ltr", "-no", "-rtl", "-x", "//", "categories", "extra", "filter", "new", "report", \'#\', \'%\', \'(\', \'*\', \'/\', \'>\', \'@\', \'[\', \'^\', \'→\', or end of input\n\n', stderr='')
brassica ./data/rules/brassica/6.1.1.7.bsc -i ./data/words/brassica/weirdness_0.5.lex
CompletedProcess(args='brassica ./data/rules/brassica/6.1.1.7.bsc -i ./data/words/brassica/weirdness_0.5.lex', returncode=0, stdout='10:11:\n   |\n10 | kʼ / k / #\n   |           ^\nunexpected newline\nexpecting "%(", \'#\', \'$\', \'%\', \'(\', \'*\', \'>\', \'@\', \'[\', \'^\', or \'_\'\n\n', stderr='')
brassica ./data/rules/brassica/6.1.1.8.bsc -i ./data/words/brassica/weirdness_0.5.lex
CompletedProcess(args='brassica ./data/rules/brassica/6.1.1.8.bsc -i ./data/words/brassica/weirdness_0.5.lex', returncode=0, stdout='13:1:\n   |\n13 | {s₁,s₃} / ʃ\n   | ^\nunexpected \'{\'\nexpecting "%(", "-1", "->", "-?", "-??", "-ltr", "-no", "-rtl", "-x", "categories", "extra", "filter", "new", "report", \'#\', \'%\', \'(\', \'*\', \'/\', \'>\', \'@\', \'[\', \'^\', \'→\', or end of input\n\n', stderr='')

Empty DataFrame
Columns: [rule, returncode, error]
Index: []